service: sourcestack-cron

provider:
  name: aws
  runtime: python3.7 # if you set >3.7, you will need a Lambda Layer for requests - see: https://aws.amazon.com/blogs/compute/upcoming-changes-to-the-python-sdk-in-aws-lambda/#:~:text=The%20Lambda%20runtimes%20for%20Python,or%20as%20a%20Lambda%20layer.
  stage: prod
  region: us-west-1 # TODO
  logRetentionInDays: 120
  versionFunctions: true
  memorySize: 512 # Lambda allocates CPU power proportional to the amount of memory provisioned
  timeout: 60
  tracing:
    lambda: true
  tags:
    deployment: serverless.com
    project: sourcestack-cron
  environment:
    AWS_ACCOUNT_ID: ${env:AWS_ACCOUNT_ID}


functions:
  sourcestack-cron:
    handler: handlers/sourcestack_cron_handler.lambda_handler
    timeout: 60
    environment:
      SOURCESTACK_KEY: ${env:SOURCESTACK_KEY}
      WP_URL: ${env:WP_URL}
      WP_PASS: ${env:WP_PASS}
    events:
      - schedule:
          rate: cron(0 1 ? * SUN *) # 1:00 am UTC every Sunday; 6:00 PM UTC-8. The last * is year


package:
  exclude:
    - .git/**
    - .terraform/**
    - terraform.tfstate
    - terraform.tfstate.backup
    - package-lock.json
    - package.json
    - node_modules/**
